#!/bin/bash

curl -X PATCH https://api.cloudflare.com/client/v4/zones/42d0ffa98300cf343537a0d691086f3a/settings/development_mode \
  -H "X-Auth-Email: maxfieldlehman@gmail.com" \
  -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
  -H "content-Type:application/json" \
  --data "{\"value\": \"$1\"}"
