#!/bin/bash

curl -X DELETE "https://api.cloudflare.com/client/v4/zones/42d0ffa98300cf343537a0d691086f3a/purge_cache" \
-H "X-Auth-Email: maxfieldlehman@gmail.com" \
-H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
-H "Content-Type:application/json" \
--data '{"purge_everything":true}'
